<?php

declare(strict_types=1);

use Rector\Config\RectorConfig;

return RectorConfig::configure()
    ->withPaths([
        __DIR__.'/bin/console',
        __DIR__.'/config',
        __DIR__.'/public',
        __DIR__.'/src',
        __DIR__.'/tests',
    ])
    ->withSkip([
        // Generated by Symfony
        __DIR__.'/config/reference.php',
    ])
    ->withCache(__DIR__.'/var/rector')
    // The PHP version comes from composer.json (php >=8.5)
    ->withPhpSets()
    ->withPreparedSets(symfonyCodeQuality: true)
    // Lets the Symfony rules see the real services; compiled by any bin/console call in dev
    ->withSymfonyContainerXml(__DIR__.'/var/cache/dev/App_KernelDevDebugContainer.xml')
;
